# Generated by Django 4.0.2 on 2022-03-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
                ('common_login_location', models.CharField(max_length=100)),
                ('common_login_time', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
