# Generated by Django 4.0.2 on 2022-03-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_userinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='common_login_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
