# Generated by Django 4.0.2 on 2022-04-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userinfo_login_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='if_auth_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='loginFailure_days',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
