# Generated by Django 4.0.2 on 2022-04-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userinfo_if_auth_login_userinfo_loginfailure_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='loginFailure_days_Tag',
            field=models.BooleanField(default=False),
        ),
    ]
