# Generated by Django 4.0.2 on 2022-04-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_userinfo_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='login_failure',
            new_name='login_failure_num',
        ),
    ]
