# Generated by Django 4.0.2 on 2022-04-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_rename_login_failure_userinfo_login_failure_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
