# Generated by Django 4.0.2 on 2022-04-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_userinfo_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='if_auth_login',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
