# Generated by Django 4.0.2 on 2022-04-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_userinfo_if_auth_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='loginFailure_days_Tag',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
