# Generated by Django 4.0.2 on 2022-04-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('level', models.CharField(max_length=8, null=True)),
                ('method', models.CharField(max_length=4, null=True)),
                ('username', models.CharField(max_length=128, null=True)),
                ('sip', models.GenericIPAddressField(null=True)),
                ('dip', models.GenericIPAddressField(null=True)),
                ('path', models.CharField(max_length=100, null=True)),
                ('status_code', models.CharField(max_length=3, null=True)),
                ('reason_phrase', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
