# Generated by Django 4.0.2 on 2022-04-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskWarning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('level', models.CharField(max_length=8, null=True)),
                ('riskDescribe', models.CharField(max_length=100, null=True)),
                ('body', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='accesslogs',
            name='body',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
