# Generated by Django 4.0.2 on 2022-04-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskWarning', '0002_userrisk_accesslogs_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrisk',
            name='body',
        ),
    ]
