# Generated by Django 4.0.2 on 2022-03-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propertyManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_location_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('auth_first_time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('if_auth_login', models.BooleanField(null=True)),
                ('auth_start_time', models.DateTimeField(auto_now=True, null=True)),
                ('auth_end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('location', models.CharField(max_length=500)),
                ('if_log_success', models.BooleanField()),
                ('if_solve', models.BooleanField(null=True)),
                ('solve_method', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='property_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_user', models.CharField(max_length=20)),
                ('share_users', models.CharField(max_length=100, null=True)),
                ('share_start_time', models.DateTimeField(auto_now_add=True)),
                ('share_end_time', models.DateTimeField(auto_now=True, null=True)),
                ('individualProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyManage.individual_property')),
            ],
        ),
    ]
