# Generated by Django 4.0.2 on 2022-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_auth',
            name='fileDescribe',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
