# Generated by Django 4.0.2 on 2022-03-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationManage', '0002_property_auth_filedescribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_auth',
            name='share_end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
