# Generated by Django 4.0.2 on 2022-03-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationManage', '0003_alter_property_auth_share_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_auth',
            name='share_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
