# Generated by Django 4.0.4 on 2022-05-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationManage', '0004_alter_property_auth_share_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='logInfo',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
