# Generated by Django 4.0.4 on 2022-05-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationManage', '0005_position_loginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='if_log_success',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='logInfo',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='user',
            field=models.CharField(max_length=128),
        ),
    ]
