# Generated by Django 4.0.4 on 2022-05-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationManage', '0006_alter_position_if_log_success_alter_position_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_location_auth',
            name='auth_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
