# Generated by Django 4.0.2 on 2022-03-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual_property',
            name='fileName',
        ),
    ]
