# Generated by Django 4.0.2 on 2022-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManage', '0002_remove_individual_property_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_property',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
