# Generated by Django 4.0.2 on 2022-04-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManage', '0004_remove_individual_property_myfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual_property',
            name='filePath',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
